name: Unit Testing

on:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'feature_cicd'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:

  run_regression:
    name: Run tests in container
    runs-on: ubuntu-latest
    steps:
      - name: Pre Cleanup
        uses: docker://ghcr.io/evertbunschoten/mlpcpp_test:latest
        with:
          entrypoint: /bin/rm 
          args: -rf src/

      - name: Run regression tests
        uses: docker://ghcr.io/evertbunschoten/mlpcpp_test:latest
        with:
          args: -b ${{ github.ref }}
      
      - name: Post Cleanup
        uses: docker://ghcr.io/evertbunschoten/mlpcpp_test:latest
        with:
          entrypoint: /bin/rm 
          args: -rf src/
